// Recieve packets (Server -> Client)

ENTER_CREDENTIALS_COMMAND = 2;
ENTER_WORLD_COMMAND = 3;
STATUS_REQUEST = 4;
SELF_INFO_REQUEST = 5;
POSITION_SEND_ENABLE = 6;
MOVE_TO_COMMAND = 7;
FULL_NPC_INFO_REQUEST = 8;
QUICK_NPC_INFO_SEND_ENABLE = 9;
FULL_NPC_INFO_BY_OID_REQUEST = 10;
FULL_PLAYER_INFO_REQUEST = 11;
QUICK_PLAYER_INFO_SEND_ENABLE = 12;
FULL_PLAYER_INFO_BY_OID_REQUEST = 13;
TARGET_COMMAND = 14;
USE_ACTION_COMMAND = 15;
USE_SKILL_COMMAND = 16;
BOT_ENABLE_COMMAND = 17;
STOP_COMMAND = 18;